Cast.create(name:"ジョエリー・リチャードソン",over_view:"ジョエリー・リチャードソン（Joely Richardson）は、イギリス・ロンドン出身の女優である。父親は映画監督のトニー・リチャードソン、母親は女優のヴァネッサ・レッドグレイヴ。姉のナターシャも女優である。幼いころからエキストラとして父親の作品に出ていたが、本人は体操選手になりたかったという。王立演劇学校（RADA）で演技を学び、1985年に映画デビューした。長身で気品のある女優である。物議を醸したテレビ映画『チャタレイ夫人の恋人』やドラマ『NIP/TUCK』でも体当たりの演技を見せている。1992年に映画プロデューサーと結婚し、同年に娘が産まれたが、2001年に別れている。",image_url:"https://image.tmdb.org/t/p/original/fgjpKio6sMD5AxOWQwAdgJQErhm.jpg",movie_id: 20810,birthday:"1965年1月9日")
DramaCastRelation.create(drama_id:66,cast_id:45)
# Drama.create(title: "",over_view: "",image_url: "", seasons_count: 0,source_url: '',category: 5)
# Season.create(title: "シーズン1", over_view: "", drama_id: 43, season_no: 1, source_url: '')
# Article.create(title: "",image: "",heading: "",trailer: "",created_at: Time.zone.now,updated_at: Time.zone.now)
# ArticleContent.create(article_id: 3,drama_id: 6,title:"",content:"\n",created_at: Time.zone.now,updated_at: Time.zone.now)
# Cast.create(name:"",over_view:"",image_url:"",movie_id: ,birthday:"年月日")
# DramaCastRelation.create(drama_id:,cast_id:)