# Drama.create(title: "24",over_view: "24時間のリアルタイムで繰り広げられる迫力のアクション操作バトル",image_url: "https://images-fe.ssl-images-amazon.com/images/I/51x0TJQ4lyL._SL300_.jpg")
# Drama.create(title: "ゴシップガール",over_view: "ゴージャスなシリーズ・フィナーレで最後の最後に頂点に立つのは誰？",image_url: "https://images-fe.ssl-images-amazon.com/images/I/516zb9SR%2B-L._SL300_.jpg")
# Drama.create(title: "シカゴ・ファイア",over_view: "1話ごとにさまざまなシチュエーションを持った迫力のレスキューシーンと、仕事に誇りを持つ彼らの雄姿が本作の大きな見どころ。
# ",image_url: "https://images-fe.ssl-images-amazon.com/images/I/51Au7MpG5uL._SL300_.jpg")
# Drama.create(title: "ウォーキング・デッド",over_view: "ゾンビで溢れかえった世界では、人間たちの殺し合いの毎日だった",image_url: "https://images-fe.ssl-images-amazon.com/images/I/51cumRw5jrL._SL300_.jpg")
# Drama.create(title: "マジシャンズ ",over_view: "「スーパーナチュラル」のスタッフが全米ベストセラー小説を基に描く、魔界ダークファンタジー",image_url: "https://images-fe.ssl-images-amazon.com/images/I/5167lKYSi8L._SL300_.jpg")
# Drama.create(title: "ゲームオブスローンズ ",over_view: "７大国間で繰り広げられる鉄の玉座を巡った歴史ファンタジー",image_url: "https://images-fe.ssl-images-amazon.com/images/I/51yB9jHqkFL._SL300_.jpg", seasons_count: 0)


# Drama.create(title: "グリム",over_view: "童話で知られるグリム兄弟の家系は、人間の姿かたちを借りて人間社会に潜む魔物（ヴェッセン）たちの正体を見抜くことができる。森深いオレゴン州ポートランドの市警察殺人課の刑事ニック・ブルクハルトは、癌で余命いくばくも無いおばのマリーから自分がグリムの末裔であることを知らされ、以来、ヴェッセンが関わる事件の解決に挑んでいく……。",image_url: "https://images-fe.ssl-images-amazon.com/images/I/61RAQxrilaL._SL300_.jpg", seasons_count: 0,source_url: 'http://www.superdramatv.com/line/grimm/')
# Season.create(title: "シーズン1", over_view: "オレゴン州ポートランド市警察殺人課の刑事ニックは、街中でふと目を引かれた美しい女性が瞬間的に魔物のような恐ろしい顔に変貌するのを目撃して驚く。その頃、市内の森をランニング中の女子大学生が殺害される事件が発生。ピンクのスニーカーに赤いパーカーを着ていた彼女は、猛獣にでも襲われたかのように無惨にも遺体が引裂かれていた。", drama_id: 7, season_no: 1, source_url: 'http://www.superdramatv.com/line/grimm/story/')
# Season.create(title: "シーズン2", over_view: "オレゴン州ポートランド市警察殺人課の刑事ニックは、街中でふと目を引かれた美しい女性が瞬間的に魔物のような恐ろしい顔に変貌するのを目撃。実はニックは、人間に紛れて存在している魔物（ヴェッセン）を狩る「グリム一族」の末裔であり、グリムとしての能力が覚醒したのだった。", drama_id: 7, season_no: 2, source_url: 'http://www.superdramatv.com/line/grimm/story/')
# Season.create(title: "シーズン3", over_view: "オレゴン州ポートランド市警察殺人課の刑事ニックは、街中で、美しい女性が瞬間的に魔物のような恐ろしい顔に変貌するのを目撃。実はニックは人間に紛れて存在している“魔物（ヴェッセン）”を狩るグリム一族の末裔であり、グリムとしての能力が覚醒したのだった。", drama_id: 7, season_no: 3, source_url: 'http://www.superdramatv.com/line/grimm/story/')
# Season.create(title: "シーズン4", over_view: "一見普通の人間だが、実は様々な魔物が人間社会に溶け込むために姿を変えただけに過ぎないヴェッセン。その存在が見えるグリム一族の末裔、ニック・ブルクハルトはポートランド市警察の刑事である。ヴェッセンに恐れられるグリムだが、ニックの親友は狼型ヴェッセン“ブルットバッド”のモンローで、ヴェッセンが絡む事件では、モンローや彼の恋人でキツネ型ヴェッセンの“フクスバウ”であるロザリーも頼もしい協力者だ。", drama_id: 7, season_no: 4, source_url: 'http://www.superdramatv.com/line/grimm/story/')
# Season.create(title: "シーズン5", over_view: "トラブルの放った矢に射抜かれ崩れ落ちたジュリエット。その直後に男たちが現れ、ニックは意識を失う。ニックが目覚めるとトラブルもジュリエットも母ケリーも消えていた……。ニックは駆けつけたハンクに事情を話し、政府の秘密組織の一員でヴェッセンであるFBI捜査官のチャベスの仕業だと訴えるも、半信半疑のハンク。ニックは「チャベスを狩る」と言い残し出て行く", drama_id: 7, season_no: 5, source_url: 'http://www.superdramatv.com/line/grimm/story/')

# Drama.create(title: "ブレイキング・バッド",over_view: "これまでに真面目に生きてきた高校の化学教師ウォルターが、ある日突然、肺ガンで余命2年と宣告される。脳性麻痺の長男に、身重の妻を抱えて、最大の心配事は今後の家族の生活費。絶望的な状況の中で、ウォルターは化学の知識を生かして違法ドラッグ（クリスタル・メス）を製造し、かつての教え子のドラッグディーラーと組んで家族に遺す現金を調達するべく、後戻りのできない犯罪へと手を染めていく——。",image_url: "https://images-fe.ssl-images-amazon.com/images/I/51ecLXX8xAL._SL300_.jpg", seasons_count: 0,source_url: 'http://www.superdramatv.com/line/breakingbad/')
# Season.create(title: "シーズン1", over_view: "ニューメキシコ州アルバカーキにある高校で、化学教師を勤めているウォルター・ホワイト。第二子を妊娠中の妻スカイラーと、脳性麻痺のため、軽度の言語障害と松葉杖を使っている高校生の長男ジュニアと暮らしている。カリフォルニア工科大学を出たウォルターは、かつては将来を嘱望された優秀な科学者だったが、現在はやる気のない生徒たちを相手に淡々と授業を行い、給与が低いため、洗車場のレジ係のアルバイトをして家計の足しにしている。", drama_id: 8, season_no: 1, source_url: 'http://www.superdramatv.com/line/breakingbad/story/')
# Season.create(title: "シーズン2", over_view: "高校の化学教師であるウォルター・ホワイトが化学の知識を生かして作った純度の高いクリスタルメスは、その色からブルーメスと呼ばれてドラッグ市場を席巻する。相棒の元教え子でドラッグディーラーのジェシー・ピンクマンは嫌がるが、ウォルターは”ハイゼンベルク”と名乗って地元のドラッグの元締めであるトゥコと直接取引をすることに。だが、取引の場でトゥコの部下ノー・ボードの発言がトゥコの怒りを買い、トゥコは彼を激しく殴りつけた挙げ句、殺してしまう。", drama_id: 8, season_no: 2, source_url: 'http://www.superdramatv.com/line/breakingbad/story/')
# Season.create(title: "シーズン3", over_view: "ジェシー・ピンクマンと共にドラッグに溺れていた恋人ジェーンが、過剰摂取により死亡した。ウォルター・ホワイトは現場にいたが、あえてジェーンを助けることはせず、廃人同然になっていたジェシーを連れ出し麻薬常習者の更生施設へと送り込む。ひとり娘を何とか立ち直らせようとしていたジェーンの父親ドナルドは、数日の休みを取った後、航空管制官として勤務中に誘導ミスをおかし、167名もの犠牲者を出す墜落事故を引き起こしてしまう。ウォルターの実家付近にも飛行機の残骸が飛来するなど、街全体が9.11以来とも言うべき暗く悲しみに沈んでいた。追悼集会が開かれる中、ウォルターは発言を求められるが自らが引き起こした事態に動揺が収まらず、意味不明なことを口走ってしまう。", drama_id: 8, season_no: 3, source_url: 'http://www.superdramatv.com/line/breakingbad/story/')
# Season.create(title: "シーズン4", over_view: "妻スカイラーに離婚を突きつけられて憔悴しきったウォルターは、高校でトラブルを起こして無期限の停職処分を受ける。そんなウォルターに表向きは成功した事業家だが裏の顔はマフィアの大物であるガスは、最新鋭の麻薬製造ラボを提供し、このビジネスに引き戻そうとする。しかし、その一方で、組織の和を乱すジェシーを外し、ウォルターには新たにゲイルという助手を付けた。ガスの真の狙いは、ゲイルにウォルターの技術の全てをマスターさせた後、ウォルターを始末して彼にラボを引き継がせようというものだった。 ", drama_id: 8, season_no: 4, source_url: 'http://www.superdramatv.com/line/breakingbad/story/')
# Season.create(title: "シーズン5", over_view: "メキシコのカルテルに復讐を果たしたガスに追い詰められたウォルターは、ジェシーをも欺き、大胆な作戦で賭けに出る。それは血縁者全員をガスに消されたヘクター・サラマンカを利用して、手製の爆弾で2人を同時に殺害するというものだった。表向きは一件落着したものの、ウォルターはガスの監視カメラの映像がオフィスに残ったままであることに気付く。ガスの死に激怒する用心棒のマイクにも監視カメラに全員が映っていると説得し、ウォルターとジェシー、マイクらは証拠を破壊する奇想天外な作戦を実行。さらにウォルターはソウルの反対を押し切ってマイクと手を組んでビジネスを再開し、流通を仕切ってくれるよう依頼。しぶしぶ引き受けるマイクはこれまでメスの原料を調達していたリディアという女と会合する。", drama_id: 8, season_no: 5, source_url: 'http://www.superdramatv.com/line/breakingbad/story/')


