Drama.create(title: "クリミナルマインド",over_view: "ＦＢＩの最強プロファイラー・ユニット”ＢＡＵ（行動分析課）”のメンバーが様々な凶悪犯罪に挑む犯罪捜査ミステリー",image_url: "https://images-fe.ssl-images-amazon.com/images/I/51AC4P-kmML._SL300_.jpg", seasons_count: 0,source_url: 'http://www.superdramatv.com/line/criminalmind/')
Season.create(title: "シーズン1", over_view: "バージニア州クワンティコにあるFBIの重要セクション、行動分析課（BAU）。彼らは無数の犯罪者たちの特徴をデータ化し、行動科学的に分析することで新たな犯罪者の行動を予測するプロファイリングのエキスパートが集まった、エリート集団である。", drama_id: 9, season_no: 1, source_url: 'http://www.superdramatv.com/line/criminalmind/story/')
Season.create(title: "シーズン2", over_view: "フィッシャー・キング事件で犯人からの銃撃を受けたエルは、生死の境をさまようも、現場復帰する。しかしＰＴＳＤを発症し、現場で問題を起こした末、自分の罪を認めないままＢＡＵを去っていった。その後ＦＢＩで10年のキャリアを持ち、ホッチナーと面識のあるエミリー・プレンティスが加入。", drama_id: 9, season_no: 2, source_url: 'http://www.superdramatv.com/line/criminalmind/story/')
Season.create(title: "シーズン3", over_view: "数々の難事件を解決してきたBAUだったが、凶悪犯罪を捜査し犯人たちと向き合い続けるうちに、メンバーたちの心も少しずつ不安にさせられ、傷つけられていく……。", drama_id: 9, season_no: 3, source_url: 'http://www.superdramatv.com/line/criminalmind/story/')
Season.create(title: "シーズン4", over_view: "ある日、ＦＢＩニューヨーク支局の責任者ケイトから旧知のホッチに協力依頼の電話が入る。事件は日中の地下鉄駅や街頭で突然男が近づき、22口径の銃で射殺するというもの。２週間で５件発生していたが、６件目の犯行で犯人が初めてタロットカードを残していった。", drama_id: 9, season_no: 4, source_url: 'http://www.superdramatv.com/line/criminalmind/story/')
Season.create(title: "シーズン5", over_view: "10年前にボストンで悪事を繰り返し、その当時ホッチも捜査にあたっていた「リーパー」と呼ばれる連続殺人犯が、活動を再開した。そしてホッチのもとにリーパーから、「追うのをやめれば襲うのをやめる」という取り引きの電話がある。", drama_id: 9, season_no: 5, source_url: 'http://www.superdramatv.com/line/criminalmind/story/')
Season.create(title: "シーズン6", over_view: "真夏のロサンゼルスでレイプ殺人が連続して発生し、BAUは現地へ飛ぶ。最初の犯行が起きたニュートン地区の担当刑事カーツバードとスパイサーが共同で捜査に当たる。「暗闇の王子」とマスコミから命名された犯人は巨大都市LAを恐怖に陥れる。", drama_id: 9, season_no: 6, source_url: 'http://www.superdramatv.com/line/criminalmind/story/')
Season.create(title: "シーズン7", over_view: "バージニア州クワンティコにあるFBIの重要セクション、行動分析課（BAU･･･Behavioral Analysis Unit）。彼らは無数の犯罪者たちの特徴をデータ化し、行動科学的に分析することで新たな犯罪者の行動を予測するプロファイリングのエキスパートが集まった、エリート集団である。", drama_id: 9, season_no: 7, source_url: 'http://www.superdramatv.com/line/criminalmind/story/')
Season.create(title: "シーズン8", over_view: "米各地では常に異常な連続犯罪が発生しており、中でも似た手口の殺人事件を繰り返す犯罪者は“シリアル・キラー”と呼ばれる。彼らの犯罪を予測し、ありとあらゆる方法で阻止するのがBAUの使命だ。シリアル・キラーに手が負えなくなった全米各地の警察から、捜査協力の依頼が届けば、すぐさま専用のジェット機に乗り、彼らは全米各地に飛んでいく。", drama_id: 9, season_no: 8, source_url: 'http://www.superdramatv.com/line/criminalmind/story/')
Season.create(title: "シーズン9", over_view: "彼らを標的にストーカーのようにつきまとう“レプリケーター”と対決して辛くも勝利したBAUチームだったが、セクションチーフであったストラウスの命を奪われてしまった。チーム・リーダーである捜査官アーロン・ホッチナーは、FBI上層部からストラウスの後任として部長の座をオファーされる。現場を去るかどうかの決断に苦悩するホッチナー。", drama_id: 9, season_no: 9, source_url: 'http://www.superdramatv.com/line/criminalmind/story/')
Season.create(title: "シーズン10", over_view: "大学教員の道を選んで去っていったブレイクの後任として、アンディ・スワンのチームにいたケイト・キャラハンがBAUにやって来る。おとり捜査で優秀な成果をあげていたようだが、実力の程はいかに。初仕事としてカリフォルニア州ベイカーズフィールドで発生中の連続殺人事件の捜査を行うこととなる。", drama_id: 9, season_no: 10, source_url: 'http://www.superdramatv.com/line/criminalmind/story/')


